language:
  - cpp

#dist: trusty

sudo: false
#sudo: required

os:
  - linux
  - osx
#  - mingw

branches:
  only:
    - master
    - dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  - CONF=debug BUILDER=clang
  - CONF=debug BUILDER=gcc

matrix:
  include:
    - os: linux
      env: CONF=debug BUILDER=gcc GCOV=--gcov
    - os: linux
      env: CONF=release BUILDER=clang
    - os: linux
      env: CONF=release BUILDER=gcc
  exclude:
    - os: mingw
      env: CONF=debug BUILDER=clang

install:
  - uname -a
  - printenv
  - pip install --user lutin


before_script:
  - cd ..
  - wget http://atria-soft.com/ci/coverage_send.py
  - wget http://atria-soft.com/ci/test_send.py
  - wget http://atria-soft.com/ci/warning_send.py
  - git clone https://github.com/generic-library/gtest-lutin.git --recursive
  - pwd
  - ls -l
  - if [ "$BUILDER" == "gcc" ]; then
        export COMPILATOR_OPTION="--compilator-version=4.9";
    else
        export COMPILATOR_OPTION="";
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        export PATH=$PATH:/Users/travis/Library/Python/2.7/bin/;
    fi
  - if [ "$TRAVIS_OS_NAME" == "mingw" ]; then
        export TARGET="-t Windows";
        export COMPILATOR_OPTION="";
    else
        export TARGET="";
    fi

script:
  - lutin -w -j4 -C -P $TARGET -c $BUILDER $COMPILATOR_OPTION -m $CONF $GCOV -p etk-test

after_script:
  - if [ "$GCOV" != "" ]; then
        python ./warning_send.py --find-path ./out/Linux_x86_64/$CONF/build/$BUILDER/etk/;
    fi
  - ./out/Linux_x86_64/$CONF/staging/$BUILDER/etk-test/usr/bin/etk-test -l6 | tee out_test.txt
  - if [ "$GCOV" != "" ]; then
        python ./test_send.py --file=out_test.txt;
        lutin -C -P -c $TARGET $BUILDER $COMPILATOR_OPTION -m $CONF -p etk?gcov;
        python ./coverage_send.py --json=out/Linux_x86_64/$CONF/build/$BUILDER/etk/etk_coverage.json;
    fi

notifications:
  email:
    - yui.heero@gmail.com

